### ISSUE TITLE
label_only flag not read correctly

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/caliban#159] opened 2020-04-23 23:19 UTC
Browser currently interprets label_only flag to be true no matter what boolean actually follows it in the url

**Comment by geneva-miller** [comment] 2020-04-23 23:24
https://github.com/vanvalenlab/caliban/blob/browser/develop/browser/blueprints.py#L186-L188

label_only and pixel_only should get the same treatment that the rgb flag gets.
Alternatively @willgraf if there are things about url construction (urls args capitalized or not?) or other ways to approach this bug, this would be a good opportunity to address them.

**Comment by willgraf** [comment] 2020-04-24 06:49
I think that [request arguments are case sensitive](https://flask.palletsprojects.com/en/1.1.x/api/#flask.Request.args) in Flask. Maybe we should assume all URLs should be lower case.

We parse the `label_only` option like:

```python
label_only = request.args.get('label_only', default=False, type=bool)
```

I would think including `label=false` in the URL args would give it a `False` value. Maybe try just not including it unless you want it to be `True`?

**Comment by ngreenwald** [comment] 2020-04-24 07:02
That's how we had it before. But then when I switched to url_encoding of
the optional args, they get included with their boolean flag:
https://github.com/vanvalenlab/caliban-toolbox/blob/4987f58972a76a916cd2ad13593cb67dff19347b/caliban_toolbox/aws_functions.py#L94

**Comment by willgraf** [comment] 2020-04-24 21:23
Closing this as I have pretty much duplicated it with the root cause in #161

**Closed by willgraf** 2020-04-24 21:23 UTC
Labels: browser, bug
